# This is a basic workflow to help you get started with Actions

name: retroarch
on:
  workflow_dispatch:
  # Build every 7 days
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create retroarch package
      run: |
        # Install tools
        sudo apt install -y jq wget tar xz-utils pv git pcregrep
        # Custom packages
        mkdir -p bin
        export PATH="$(pwd)/bin:$PATH"
        wget -q --show-progress --progress=dot:binary -O bin/jq \
          https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-amd64
        chmod +x ./bin/*
        # Build packages
        ( HOME="$(pwd)" FIM_DEBUG=1 FIM_FIFO=0 ./retroarch/build-arch.sh )
        # Dist folder created by build-arch
        mv ./retroarch/dist .

    - name: Set permissions for dist directory
      run: |
        sudo chown -R "$(id -u)":"$(id -g)" dist/
        sudo chmod -R 766 dist/

    - name: Upload artifact to release
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifacts_build
        path: 'dist'

    - name: Compute Short SHA
      id: ssha
      run: |
        echo "ssha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    outputs:
      ssha: ${{ steps.ssha.outputs.ssha }}

  release:
      permissions: write-all
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: artifacts_build

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: continuous-retroarch-gnu-x86_64
            automatic_release_tag: retroarch-gnu-x86_64
            prerelease: false
            draft: false
            files: |
              artifacts_build
            repo_token: ${{ secrets.GITHUB_TOKEN }}
